name: build PR

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'zulu'
          cache: 'maven'
      - name: Set up CI environment
        run: .github/setup.sh
      - name: Execute the build
        run: .github/build.sh
